name: iSeparate
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ffmpeg
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - protobuf<4
    - librosa
    - pyyaml
    - tqdm
    - matplotlib
    - tensorboard
    - julius
    - wget
    - stempeg
    - musdb
    - museval
    - norbert
    - git+https://github.com/NVIDIA/dllogger#egg=dllogger
    - pytest
    - torch
    - torchaudio
